version: '3'
services:
  # milk-nest:
  #   container_name: application
  #   build: .
  #   env_file: .env
  #   ports:
  #     - '3000:3000'
  #     - '9229:9229'
  #   command: pnpm start:dev
  #   volumes:
  #     - ./src:/home/app/src:cached
  #   depends_on:
  #     - nest-mongo

  nest-mongo:
    image: mongo:3.4
    container_name: nest-mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./.data/mongo:/data/db:cached